from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    browser=p.chromium.launch(channel='chrome',headless=True)
    for width in (390,1440):
        page=browser.new_page(viewport={'width':width,'height':900})
        page.route('**/api/get_groups',lambda r:r.fulfill(json={'ok':True,'groups':[{'id':'test-group','name':'Test Group','member_count':2}]}))
        page.route('**/api/group_control_preferences/*',lambda r:r.fulfill(json={'ok':True,'preferences':{'only_sharers':False,'low_likes':False},'control_mode':'comments'}))
        page.route('**/api/get_group_members/*',lambda r:r.fulfill(json={'ok':True,'members':[],'usernames':[]}))
        page.route('**/api/get_group_posts/*',lambda r:r.fulfill(json={'ok':True,'posts':[]}))
        page.goto('http://127.0.0.1:5087/')
        options=page.locator('#homeOptions')
        assert not options.evaluate('e=>e.open')
        page.locator('#groupDropdown .dropdown-trigger').click()
        page.locator('#groupDropdown .dropdown-option').filter(has_text='Test Group').click()
        assert options.evaluate('e=>e.open')
        options.locator('summary').click()
        assert not options.evaluate('e=>e.open')
        options.locator('summary').focus();page.keyboard.press('Enter')
        assert options.evaluate('e=>e.open')
        page.wait_for_function('!window.isPostsLoading && !window.isMembersLoading')
        assert options.evaluate('e=>e.open')
        assert page.locator('#controlComments').is_visible()
        options.locator('summary').click()
        page.evaluate('validateForm()')
        assert not options.evaluate('e=>e.open')
        page.close()
    browser.close()
print('Group selection opens options; manual collapse, keyboard reopening and validation preserve the chosen state on mobile/desktop.')
